/*
 Copyright (c) 2015-2017, Kotaro Endo.
 All rights reserved.
 
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:
 
 1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
 
 2. Redistributions in binary form must reproduce the above
    copyright notice, this list of conditions and the following
    disclaimer in the documentation and/or other materials provided
    with the distribution.
 
 3. Neither the name of the copyright holder nor the names of its
    contributors may be used to endorse or promote products derived
    from this software without specific prior written permission.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

const intrinsicFunctions = {
    "Object.Call": Object_Call,
    "Object.Construct": Object_Construct,
    "Function.Call": Function_Call,
    "Function.Construct": Function_Construct,
    "Array.Call": Array_Call,
    "Array.Construct": Array_Construct,
    "String.Call": String_Call,
    "String.Construct": String_Construct,
    "Boolean.Call": Boolean_Call,
    "Boolean.Construct": Boolean_Construct,
    "Number.Call": Number_Call,
    "Number.Construct": Number_Construct,
    "Date.Call": Date_Call,
    "Date.Construct": Date_Construct,
    "RegExp.Call": RegExp_Call,
    "RegExp.Construct": RegExp_Construct,
    "Error.Call": Error_Call,
    "Error.Construct": Error_Construct,
    "EvalError.Call": EvalError_Call,
    "EvalError.Construct": EvalError_Construct,
    "RangeError.Call": RangeError_Call,
    "RangeError.Construct": RangeError_Construct,
    "ReferenceError.Call": ReferenceError_Call,
    "ReferenceError.Construct": ReferenceError_Construct,
    "SyntaxError.Call": SyntaxError_Call,
    "SyntaxError.Construct": SyntaxError_Construct,
    "TypeError.Call": TypeError_Call,
    "TypeError.Construct": TypeError_Construct,
    "URIError.Call": URIError_Call,
    "URIError.Construct": URIError_Construct,
    "Global.eval": Global_eval,
    "Global.parseInt": Global_parseInt,
    "Global.parseFloat": Global_parseFloat,
    "Global.isNaN": Global_isNaN,
    "Global.isFinite": Global_isFinite,
    "Global.decodeURI": Global_decodeURI,
    "Global.decodeURIComponent": Global_decodeURIComponent,
    "Global.encodeURI": Global_encodeURI,
    "Global.encodeURIComponent": Global_encodeURIComponent,
    "Global.escape": Global_escape,
    "Global.unescape": Global_unescape,
    "Object.getPrototypeOf": Object_getPrototypeOf,
    "Object.getOwnPropertyDescriptor": Object_getOwnPropertyDescriptor,
    "Object.getOwnPropertyNames": Object_getOwnPropertyNames,
    "Object.create": Object_create,
    "Object.defineProperty": Object_defineProperty,
    "Object.defineProperties": Object_defineProperties,
    "Object.seal": Object_seal,
    "Object.freeze": Object_freeze,
    "Object.preventExtensions": Object_preventExtensions,
    "Object.isSealed": Object_isSealed,
    "Object.isFrozen": Object_isFrozen,
    "Object.isExtensible": Object_isExtensible,
    "Object.keys": Object_keys,
    "Object.prototype.toString": Object_prototype_toString,
    "Object.prototype.toLocaleString": Object_prototype_toLocaleString,
    "Object.prototype.valueOf": Object_prototype_valueOf,
    "Object.prototype.hasOwnProperty": Object_prototype_hasOwnProperty,
    "Object.prototype.isPrototypeOf": Object_prototype_isPrototypeOf,
    "Object.prototype.propertyIsEnumerable": Object_prototype_propertyIsEnumerable,
    "get Object.prototype.__proto__": get_Object_prototype___proto__,
    "set Object.prototype.__proto__": set_Object_prototype___proto__,
    "Function.prototype.toString": Function_prototype_toString,
    "Function.prototype.apply": Function_prototype_apply,
    "Function.prototype.call": Function_prototype_call,
    "Function.prototype.bind": Function_prototype_bind,
    "get Function.prototype.name": get_Function_prototype_name,
    "Array.isArray": Array_isArray,
    "Array.prototype.toString": Array_prototype_toString,
    "Array.prototype.toLocaleString": Array_prototype_toLocaleString,
    "Array.prototype.concat": Array_prototype_concat,
    "Array.prototype.join": Array_prototype_join,
    "Array.prototype.pop": Array_prototype_pop,
    "Array.prototype.push": Array_prototype_push,
    "Array.prototype.reverse": Array_prototype_reverse,
    "Array.prototype.shift": Array_prototype_shift,
    "Array.prototype.slice": Array_prototype_slice,
    "Array.prototype.sort": Array_prototype_sort,
    "Array.prototype.splice": Array_prototype_splice,
    "Array.prototype.unshift": Array_prototype_unshift,
    "Array.prototype.indexOf": Array_prototype_indexOf,
    "Array.prototype.lastIndexOf": Array_prototype_lastIndexOf,
    "Array.prototype.every": Array_prototype_every,
    "Array.prototype.some": Array_prototype_some,
    "Array.prototype.forEach": Array_prototype_forEach,
    "Array.prototype.map": Array_prototype_map,
    "Array.prototype.filter": Array_prototype_filter,
    "Array.prototype.reduce": Array_prototype_reduce,
    "Array.prototype.reduceRight": Array_prototype_reduceRight,
    "String.fromCharCode": String_fromCharCode,
    "String.prototype.toString": String_prototype_toString,
    "String.prototype.valueOf": String_prototype_valueOf,
    "String.prototype.charAt": String_prototype_charAt,
    "String.prototype.charCodeAt": String_prototype_charCodeAt,
    "String.prototype.concat": String_prototype_concat,
    "String.prototype.indexOf": String_prototype_indexOf,
    "String.prototype.lastIndexOf": String_prototype_lastIndexOf,
    "String.prototype.localeCompare": String_prototype_localeCompare,
    "String.prototype.match": String_prototype_match,
    "String.prototype.replace": String_prototype_replace,
    "String.prototype.search": String_prototype_search,
    "String.prototype.slice": String_prototype_slice,
    "String.prototype.split": String_prototype_split,
    "String.prototype.substring": String_prototype_substring,
    "String.prototype.toLowerCase": String_prototype_toLowerCase,
    "String.prototype.toLocaleLowerCase": String_prototype_toLocaleLowerCase,
    "String.prototype.toUpperCase": String_prototype_toUpperCase,
    "String.prototype.toLocaleUpperCase": String_prototype_toLocaleUpperCase,
    "String.prototype.trim": String_prototype_trim,
    "String.prototype.substr": String_prototype_substr,
    "Boolean.prototype.toString": Boolean_prototype_toString,
    "Boolean.prototype.valueOf": Boolean_prototype_valueOf,
    "Number.prototype.toString": Number_prototype_toString,
    "Number.prototype.toLocaleString": Number_prototype_toLocaleString,
    "Number.prototype.valueOf": Number_prototype_valueOf,
    "Number.prototype.toFixed": Number_prototype_toFixed,
    "Number.prototype.toExponential": Number_prototype_toExponential,
    "Number.prototype.toPrecision": Number_prototype_toPrecision,
    "Math.abs": Math_abs,
    "Math.acos": Math_acos,
    "Math.asin": Math_asin,
    "Math.atan": Math_atan,
    "Math.atan2": Math_atan2,
    "Math.ceil": Math_ceil,
    "Math.cos": Math_cos,
    "Math.exp": Math_exp,
    "Math.floor": Math_floor,
    "Math.log": Math_log,
    "Math.max": Math_max,
    "Math.min": Math_min,
    "Math.pow": Math_pow,
    "Math.random": Math_random,
    "Math.round": Math_round,
    "Math.sin": Math_sin,
    "Math.sqrt": Math_sqrt,
    "Math.tan": Math_tan,
    "Date.parse": Date_parse,
    "Date.UTC": Date_UTC,
    "Date.now": Date_now,
    "Date.prototype.toString": Date_prototype_toString,
    "Date.prototype.toDateString": Date_prototype_toDateString,
    "Date.prototype.toTimeString": Date_prototype_toTimeString,
    "Date.prototype.toLocaleString": Date_prototype_toLocaleString,
    "Date.prototype.toLocaleDateString": Date_prototype_toLocaleDateString,
    "Date.prototype.toLocaleTimeString": Date_prototype_toLocaleTimeString,
    "Date.prototype.valueOf": Date_prototype_valueOf,
    "Date.prototype.getTime": Date_prototype_getTime,
    "Date.prototype.getFullYear": Date_prototype_getFullYear,
    "Date.prototype.getUTCFullYear": Date_prototype_getUTCFullYear,
    "Date.prototype.getMonth": Date_prototype_getMonth,
    "Date.prototype.getUTCMonth": Date_prototype_getUTCMonth,
    "Date.prototype.getDate": Date_prototype_getDate,
    "Date.prototype.getUTCDate": Date_prototype_getUTCDate,
    "Date.prototype.getDay": Date_prototype_getDay,
    "Date.prototype.getUTCDay": Date_prototype_getUTCDay,
    "Date.prototype.getHours": Date_prototype_getHours,
    "Date.prototype.getUTCHours": Date_prototype_getUTCHours,
    "Date.prototype.getMinutes": Date_prototype_getMinutes,
    "Date.prototype.getUTCMinutes": Date_prototype_getUTCMinutes,
    "Date.prototype.getSeconds": Date_prototype_getSeconds,
    "Date.prototype.getUTCSeconds": Date_prototype_getUTCSeconds,
    "Date.prototype.getMilliseconds": Date_prototype_getMilliseconds,
    "Date.prototype.getUTCMilliseconds": Date_prototype_getUTCMilliseconds,
    "Date.prototype.getTimezoneOffset": Date_prototype_getTimezoneOffset,
    "Date.prototype.setTime": Date_prototype_setTime,
    "Date.prototype.setMilliseconds": Date_prototype_setMilliseconds,
    "Date.prototype.setUTCMilliseconds": Date_prototype_setUTCMilliseconds,
    "Date.prototype.setSeconds": Date_prototype_setSeconds,
    "Date.prototype.setUTCSeconds": Date_prototype_setUTCSeconds,
    "Date.prototype.setMinutes": Date_prototype_setMinutes,
    "Date.prototype.setUTCMinutes": Date_prototype_setUTCMinutes,
    "Date.prototype.setHours": Date_prototype_setHours,
    "Date.prototype.setUTCHours": Date_prototype_setUTCHours,
    "Date.prototype.setDate": Date_prototype_setDate,
    "Date.prototype.setUTCDate": Date_prototype_setUTCDate,
    "Date.prototype.setMonth": Date_prototype_setMonth,
    "Date.prototype.setUTCMonth": Date_prototype_setUTCMonth,
    "Date.prototype.setFullYear": Date_prototype_setFullYear,
    "Date.prototype.setUTCFullYear": Date_prototype_setUTCFullYear,
    "Date.prototype.toUTCString": Date_prototype_toUTCString,
    "Date.prototype.toISOString": Date_prototype_toISOString,
    "Date.prototype.toJSON": Date_prototype_toJSON,
    "Date.prototype.getYear": Date_prototype_getYear,
    "Date.prototype.setYear": Date_prototype_setYear,
    "RegExp.prototype.exec": RegExp_prototype_exec,
    "RegExp.prototype.test": RegExp_prototype_test,
    "RegExp.prototype.toString": RegExp_prototype_toString,
    "Error.prototype.toString": Error_prototype_toString,
    "get Error.prototype.stack": get_Error_prototype_stack,
    "Error.prototype.getStackTraceEntry": Error_prototype_getStackTraceEntry,
    "JSON.parse": JSON_parse,
    "JSON.stringify": JSON_stringify,
    "_ThrowTypeError": ThrowTypeError,
    "_ReturnUndefined": ReturnUndefined,
    "Buffer.Call": Buffer_Call,
    "Buffer.Construct": Buffer_Construct,
    "Buffer.isEncoding": Buffer_isEncoding,
    "Buffer.isBuffer": Buffer_isBuffer,
    "Buffer.byteLength": Buffer_byteLength,
    "Buffer.concat": Buffer_concat,
    "Buffer.compare": Buffer_compare,
    "Buffer.prototype.write": Buffer_prototype_write,
    "Buffer.prototype.writeUIntLE": Buffer_prototype_writeUIntLE,
    "Buffer.prototype.writeUIntBE": Buffer_prototype_writeUIntBE,
    "Buffer.prototype.writeIntLE": Buffer_prototype_writeIntLE,
    "Buffer.prototype.writeIntBE": Buffer_prototype_writeIntBE,
    "Buffer.prototype.readUIntLE": Buffer_prototype_readUIntLE,
    "Buffer.prototype.readUIntBE": Buffer_prototype_readUIntBE,
    "Buffer.prototype.readIntLE": Buffer_prototype_readIntLE,
    "Buffer.prototype.readIntBE": Buffer_prototype_readIntBE,
    "Buffer.prototype.toString": Buffer_prototype_toString,
    "Buffer.prototype.toJSON": Buffer_prototype_toJSON,
    "Buffer.prototype.equals": Buffer_prototype_equals,
    "Buffer.prototype.compare": Buffer_prototype_compare,
    "Buffer.prototype.copy": Buffer_prototype_copy,
    "Buffer.prototype.slice": Buffer_prototype_slice,
    "Buffer.prototype.readUInt8": Buffer_prototype_readUInt8,
    "Buffer.prototype.readUInt16LE": Buffer_prototype_readUInt16LE,
    "Buffer.prototype.readUInt16BE": Buffer_prototype_readUInt16BE,
    "Buffer.prototype.readUInt32LE": Buffer_prototype_readUInt32LE,
    "Buffer.prototype.readUInt32BE": Buffer_prototype_readUInt32BE,
    "Buffer.prototype.readInt8": Buffer_prototype_readInt8,
    "Buffer.prototype.readInt16LE": Buffer_prototype_readInt16LE,
    "Buffer.prototype.readInt16BE": Buffer_prototype_readInt16BE,
    "Buffer.prototype.readInt32LE": Buffer_prototype_readInt32LE,
    "Buffer.prototype.readInt32BE": Buffer_prototype_readInt32BE,
    "Buffer.prototype.readFloatLE": Buffer_prototype_readFloatLE,
    "Buffer.prototype.readFloatBE": Buffer_prototype_readFloatBE,
    "Buffer.prototype.readDoubleLE": Buffer_prototype_readDoubleLE,
    "Buffer.prototype.readDoubleBE": Buffer_prototype_readDoubleBE,
    "Buffer.prototype.writeUInt8": Buffer_prototype_writeUInt8,
    "Buffer.prototype.writeUInt16LE": Buffer_prototype_writeUInt16LE,
    "Buffer.prototype.writeUInt16BE": Buffer_prototype_writeUInt16BE,
    "Buffer.prototype.writeUInt32LE": Buffer_prototype_writeUInt32LE,
    "Buffer.prototype.writeUInt32BE": Buffer_prototype_writeUInt32BE,
    "Buffer.prototype.writeInt8": Buffer_prototype_writeInt8,
    "Buffer.prototype.writeInt16LE": Buffer_prototype_writeInt16LE,
    "Buffer.prototype.writeInt16BE": Buffer_prototype_writeInt16BE,
    "Buffer.prototype.writeInt32LE": Buffer_prototype_writeInt32LE,
    "Buffer.prototype.writeInt32BE": Buffer_prototype_writeInt32BE,
    "Buffer.prototype.writeFloatLE": Buffer_prototype_writeFloatLE,
    "Buffer.prototype.writeFloatBE": Buffer_prototype_writeFloatBE,
    "Buffer.prototype.writeDoubleLE": Buffer_prototype_writeDoubleLE,
    "Buffer.prototype.writeDoubleBE": Buffer_prototype_writeDoubleBE,
    "Buffer.prototype.fill": Buffer_prototype_fill,
    "Global.setSystemProperty": Global_setSystemProperty,
    "Global.getSystemProperty": Global_getSystemProperty,
    "Global.setSystemHandler": Global_setSystemHandler,
    "Global.getSystemHandler": Global_getSystemHandler,
    "Global.removeSystemHandler": Global_removeSystemHandler,
    "OpaqueFunction.Call": OpaqueFunction_Call,
    "OpaqueFunction.Construct": OpaqueFunction_Construct,
};

const intrinsicFunctionNameMap = new WeakMap();

(function() {
    for (var name in intrinsicFunctions) {
        var func = intrinsicFunctions[name];
        intrinsicFunctionNameMap.set(func, name);
    }
})();

function getIntrinsicFunctionName(func) {
    if (func === undefined) {
        return "";
    }
    var name = intrinsicFunctionNameMap.get(func);
    assert(name !== undefined, func);
    return name;
}

function getIntrinsicFunction(name) {
    if (name === "") {
        return undefined;
    }
    var func = intrinsicFunctions[name];
    assert(func !== undefined, name);
    return func;
}
